# Generated by Django 5.1.6 on 2025-02-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='location',
        ),
        migrations.AddField(
            model_name='seminar',
            name='photo',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seminar',
            name='time',
            field=models.TimeField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seminar',
            name='date',
            field=models.DateField(),
        ),
    ]
