# Generated by Django 5.1.6 on 2025-02-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_seminar_location_seminar_photo_seminar_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
